#!/bin/bash

# Set $MARMOT_PATH to JAR and models
# Pass input file, output file (both gz), model (no path)
# Requires cow-marmot-join to merge new annotations into COW file.

set -e
set -u

java -cp ${MARMOT_PATH}/marmot.jar marmot.morph.cmd.Annotator --model-file ${MARMOT_PATH}/de.marmot --test-file form-index=0,<(gunzip -c ${1} | sed 's/^<s>\|<\/s>$//; /^</d; s/&quot;/"/g; s/&apos;/'"'"'/g; s/&lt;/</g; s/&gt;/>/g; s/&amp;/\&/g;') --pred-file ${2}

