#!/usr/bin/python

import gzip
import argparse
import os.path
import sys

parser = argparse.ArgumentParser()
parser.add_argument("xml", help="XML file to which to add token annotations.")
parser.add_argument("ann", help="TSV file which contains annotations to be added.")
parser.add_argument("att", help="S-attribute to which to add the annotations.")
parser.add_argument("out", help="Output gzipped XML file.")
args = parser.parse_args()

if not os.path.exists(args.xml) or not os.path.exists(args.ann):
    sys.exit("One or more input files do not exist.")

if os.path.exists(args.out):
    sys.exit("Output file exists!")

if args.out == args.xml or args.out == args.ann:
    sys.exit("Inputs and output cannot be the same file.")

xml_file=gzip.open(args.xml)
ann_file=gzip.open(args.ann)
out_file=gzip.open(args.out, 'wb')

# This should not be hardcoded. TODO RS FIX!
control = 1  # Which field in the new annotations is the control to match against XML s-attr.
skip = 2     # How many annotations from ann_file NOT to merge (starting at beginning).

# This presupposes that we add annotations to s-att which has
# annotations already. Such as "<doc " (note the blank).
searcher = "<" + args.att + " "

for x in xml_file:
    if searcher in x:
	x = x.strip()

	# Read and split the annotation.
	v = ann_file.readline().strip()
	vs = v.split("\t")

	if vs[control] in x:
	    out_file.write(x[0:len(x)-1] + " " + " ".join(vs[skip:len(vs)]) + ">\n")
	else:
	    sys.stderr.write("ERROR! No control match: " + " ".join(vs) + " ::: " + x + "\n")
    else:
	x = x.strip()
	
	# Pre-filter for input fucked up with <no-type> by mate-tools.
	x = x.replace("|<no-type>|", "|")

	out_file.write(x + "\n")

	

xml_file.close()
ann_file.close()
out_file.close()
