#!/bin/bash

echo =======================================================================
echo This script generates token annotations to be later merged with the 
echo original files/annotations. Do not delete the inputs!
echo =======================================================================

MALTJAR="/home/rsling/usr/local/maltparser-1.7.2/maltparser-1.7.2.jar"
MALTDIR="/home/rsling/usr/local/texrex/scripts/annotate/de/"
MALTMOD="tigercow-de.mco"

inf=$1
outf=$2
tmpinf=$(basename $inf .xml.gz)
tmpf1=$tmpinf".preparse"
tmpf2=$tmpinf".parsed"

echo "======= SUMMARY ======="
echo "Input:        $inf"
echo "TMP infix:    $tmpinf"
echo "Preprocessed: $tmpf1"
echo "Parsed:       $tmpf2"
echo "Output:       $outf"
echo "======================="

echo
echo "Preprocessing $inf to $tmpf1..."

gunzip -c $1 | \
  sed '/^<s>\|<\/s>/ s/^.*$//' | \
  sed '/^</d' | \
  sed 's/\&apos;/'"'"'/g; s/\&quot;/"/g; s/\&amp;/\&/g;' | \
  sed 's/^\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	[^	]\+$/_	\1	\3	\2	\2	_	_	_	_	_/' > $tmpf1

echo
echo "Parsing $tmpf1 to $tmpf2..."

java -Xmx32g -jar $MALTJAR -w $MALTDIR -c $MALTMOD -i $tmpf1 -o $tmpf2 -m parse

exit

echo
echo "Deleting $tmpf1..."
#\rm $tmpf1

echo
echo "Post-processing $tmpf2 to $outf..."

cat $tmpf2 | \
    sed '1 s/^.*$/&\n/' | \
    sed '/^1	!<s_~_/ { s/_~_/ /g; s/^1	!\(<[^>]\+>\).\+$/\1/ }' | \
    sed '/^</! { s/\&/\&amp;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g; }' | \
    cut -f 1,2,3,4,7,8 | \
    sed '/^</! { s/\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	\([^	]\+\)/\2	\4	\3	\1	\5	\6/}' | \
    sed '1! s/^<s/<\/s>\n&/' | \
    sed '/^\s*$/d' | \
    sed -e "\$a<\/s>" | \
    gzip -c > $outf 

echo
echo "Deleting $tmpf2..."
#\rm $tmpf2

echo
echo "Done?"
echo
