#!/bin/bash

export LC_ALL="de_DE.utf8"

TOKCONFIG="/Users/felix/NLP/cow/src/de/tokconfig-de-cow"

# remove leading spaces
  sed 's/^ *//g' | \
# remove trailing spaces
  sed 's/ *$//g' | \
# in tag lines (<) replace spaces by _~_ for ucto
  sed '/^</ s/ \+/_~_/g' | \

# any non-word character that is repeated more often than thrice, reduce to three
#  TODO Re-enable after EmpiriST!
#  sed '/^[^<]/ s/\(\W\)\1\{3,\}/\1\1\1/g' | \

# make entities ucto-compatible: insert blanks around, make literal ' and "
  sed 's/ *\&amp; */ \&amp; /g' | \
  sed 's/\&apos;\&apos;/"/g' | \
  sed "s/\\\&apos;/'/g"|  \
  sed "s/\&apos;/'/g" | \
  sed 's/&quot;/"/g' | \
  sed 's/ *\&gt; */ \&gt; /g' | \
  sed 's/ *\&lt; */ \&lt; /g' | \

# safe obfuscated email addresses
  sed '/^[^<]/ s/\([a-zA-Z0-9.-]\+\) *\[at\] *\([a-zA-Z0-9.-]\+\) *\[dot\]\ *\([a-zA-Z0-9.-]\+\)/\1ÜCTÖÄT\2ÜCTÖDÖT\3/g' | \

# Ucto eats - in Kay-M. and similar names
  sed '/^[^<]/ s/\([A-ZÄÖÜ][a-zäöüß]\+\)-\([A-ZÄÖÜ]\)\./\1ÜCTÖNÄÄÄ\2ÜCTÖNÖÖÖ/g' | \

# safe filename regions
  sed '/^[^<]/ s/\([^ ]\+\.\)\(wav\|mp3\|ogg\|flac\|aif\|aiff\|wma\|mpa\|flv\|avi\|mpg\|mpeg\|mp4\|3g2\|3gp\|m4v\|mov\|png\|jpg\|jpeg\|gif\|bmp\|tif\|tiff\|css\|js\|doc\|docx\|xls\|xlsx\|pps\|ppt\|pptx\|pages\|rtf\|odt\|ods\|odp\|pdf\|ps\|eps\|tex\|txt\|zip\|gzip\|tar\|7z\|rar\|iso\|bin\|cue\|dmg\|rpm\|deb\|pkg\)/ ÜCTÖFÜNÄb\1\2ÜCTÖFÜNÄe /g' | \

# Safe DOI regions
  sed 's/\(DOI\|doi\)\( :\|: \| : \)\(10\.[0-9.\/a-z_-]\+\)/ \1 \2 ÜCTÖDÖIb\3ÜCTÖDÖIe /g' | \
  sed 's/\(DOI\|doi\):\(10\.[0-9.\/a-z_-]\+\)/ ÜCTÖDÖIb\1:\2ÜCTÖDÖIe /g' | \

# Safe ISBN regions
  sed '/^[^<]/ s/\(ISBN *[-0-9]\+[0-9xX]\)/ ÜCTÖISBNb\1ÜCTÖISBNe /' | \

# protect content-type
  sed '/^[^<]/ s/\(text\|multipart\|message\|image\|audio\|application\)\/\([a-z0-9]\+\)/ÜCTÖCÖTÜb\1\/\2ÜCTÖCÖTÜe/g'  | \

# Make sure dates are properly processed and not S-tokenized
  sed '/^[^<]/ s/\([0-9]\{2,4\}\)-\([0-9]\{1,2\}\)-\([0-9]\{1,2\}\)/ \1ÜCTÖHÜ \2ÜCTÖHÜ \3 /g' | \
  sed '/^[^<]/ s/\([0-9]\{1,2\}\)\.\([0-9]\{1,2\}\)\.\([0-9]\{4\}\)/ \1ÜCTÖPÜ \2ÜCTÖPÜ \3 /g' | \
  sed '/^[^<]/ s/\([0-9]\{1,2\}\)\.\([0-9]\{1,2\}\)\.\([0-9]\{2\}\)/ \1ÜCTÖPÜ \2ÜCTÖPÜ \3 /g' | \

# Make sure quotes are separated 
  sed '/^[^<]/ s/\(["“”‟″˝„‚]\)/ \1 /g' | \
      
# insert blanks to make Ucto tokenize x-to-y hyphen constructs correctly
  sed '/^[^<]/ s/\(^\|[^a-zäöüßA-ZÄÖÜ]\)\([0-9.]\+\)\(\s*\)-\(\s*\)\([0-9.]\+\)\([^a-zäöüßA-ZÄÖÜ]\|$\)/\1\2 - \5\6/g' | \
  sed '/^[^<]/ s/\(^\|[^a-zäöüßA-ZÄÖÜ]\)\([0-9.]\+\)\.\(\s*\)-\(\s*\)\([0-9.]\+\)\([^a-zäöüßA-ZÄÖÜ]\|$\)/\1\2ÜCTÖNÖSÖ - \5\6/g' | \
# keep the %$&§*-iest tokenizer in the world from not s-splitting numbers and dates
  sed '/^[^<]/ s/\([0-9]\)\.\s*\([^A-ZÄÖÜ0-9]\)/\1 ÜCTÖNÖSÖ \2/g' | \
# a certain %&/§$" tokenizer eats brackets before abbreviations
  sed '/^[^<]/ s/(/( /g' | \
# This is similar: (Haus-)frieden
  sed '/^[^<]/ s/\([a-zA-ZäöüÄÖÜß]-\))/\1 )/g' | \
  ucto -n -P -c $TOKCONFIG | \

# fix obf. email addresses
  sed 's/ÜCTÖÄT/[at]/g; s/ÜCTÖDÖT/[dot]/g;' | \

# fix file names
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ä]\+\)ÜCTÖNÖSÖ\([^Ä]\+ÜCTÖFÜNÄe\)/\1.\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/\(ÜCTÖFÜNÄb[^Ü]\+\) \([^Ü]\+ÜCTÖFÜNÄe\)/\1\2/g' | \
  sed 's/ÜCTÖFÜNÄb\([^Ü]\+\)ÜCTÖFÜNÄe/\1/g' | \

# undo do-not-s-tokenize-dates hack
  sed 's/ ÜCTÖNÖSÖ/. /g' | \

# restore names like Kay-M.
  sed 's/\([^ ]\+\)ÜCTÖNÄÄÄ\([^ ]\+\)ÜCTÖNÖÖÖ/\1-\2./g' | \

# restore dates with hyphens and periods
  sed 's/ÜCTÖHÜ/-/g' | \
  sed 's/ÜCTÖPÜ/./g' | \

# restore content types
  sed 's/ÜCTÖCÖTÜb\([^Ü]\+\)ÜCTÖCÖTÜe/ \1 /g' | \


# fix ISBNs
  sed 's/\(ÜCTÖISBNb.\+\) \(.\+ÜCTÖISBNe\)/\1\2/g' | \
  sed 's/\(ÜCTÖISBNb.\+\) \(.\+ÜCTÖISBNe\)/\1\2/g' | \
  sed 's/\(ÜCTÖISBNb.\+\) \(.\+ÜCTÖISBNe\)/\1\2/g' | \
  sed 's/\(ÜCTÖISBNb.\+\) \(.\+ÜCTÖISBNe\)/\1\2/g' | \
  sed 's/\(ÜCTÖISBNb.\+\) \(.\+ÜCTÖISBNe\)/\1\2/g' | \
  sed 's/\(ÜCTÖISBNb.\+\) \(.\+ÜCTÖISBNe\)/\1\2/g' | \
  sed 's/ÜCTÖISBNbISBN\([^Ü]\+\)ÜCTÖISBNe/ISBN \1/g' | \

# fix DOIs
  sed 's/ÜCTÖDÖIb\([^Ü]\+\)ÜCTÖDÖIe/\1/g' | \

# hack cleanup, just to make sure
  sed 's/ÜCTÖ[A-ZÜÖÄ]\+\(b\|e\|\)//g' | \

# make *bla* compatible with EmpiriST
  sed 's/\*\([^ *]\+\)\*/* \1 */g' | \

# sentences with opening ( followed by sentences with closing ) are merged (see sed N command!)
  sed '/^[^<]/ { /^.*( \([^)]\+\|\)$/ {N; /\n[^(]* )/ s/\n/ /; } }' | \
# any line without ANY < or > is a sentence, insert <s></s> (still in ONE LINE!)
  sed -e '/^[^<>]\+$/ s/^\(.\+\)$/<s> \1 <\/s>/' | \
# non-XML-tag material AFTER a tag in a line which does not end in a tag is a sent, insert <s>
  sed 's/> \([^<>]\+\)$/>\n<s> \1 <\/s>/' | \
# sed  lines which contain [.!?] in the middle followed by lowercase are mostly non-detected sentence boundaries, split
  sed '/^<s>.\+ [.?!] [[:lower:]].\+<\/s>$/ s/ \([.?!]\) \([[:lower:]]\)/ \1 <\/s>\n<s>\n\2/g ' | \
# "usw." or "etc." followd by upper-case letter is usually an undetected sentence boundary.
  sed '/^<s>/ s/\(usw\.\|usf\.\|pp\.\|etc\.\|a\.a\.O\.\|u\.v\.a\.m\.\|u\.v\.m\.\|[uUoO]\.[Ää]\.\) \([A-ZÄÖÜ]\)/\1<\/s>\n<s>\2/g' | \
# sentences longer than 400 chars are un-sentenced (remove <s></s>)
  sed '/^<s>.\{400,\}<\/s>$/ s/^<s>\(.\+\)<\/s>$/\1/' | \
# sentences shorter than 15 chars are un-sentenced
  sed '/^<s>.\{,15\}<\/s>$/ s/^<s>\(.\+\)<\/s>$/\1/' | \
# sentences shorter than 3 tokens are un-sentenced
  sed 's/^<s> \([^ ]\+\( [^ ]\+\)\{0,2\}\) <\/s>$/\1/' | \
# sentences with boilerplate potential are un-sentenced
  sed 's/^<s> \(.*\(©\|[cC]opyright\|vBulletin\|[aA]ll [rR]ights\|Du bist hier :\|weiterlesen \.\.\.\|mehr \.\.\.\|\[mehr\]\|\[weiter\]\|\[weiterlesen\]\| [Tt]el \| [Ff]on \| [Pp]hone \).*\) <\/s>$/\1/' | \
# potential English sentences are un-sentenced
  sed 's/^<s> \(\(.* \|\)\([Aa]nd\|[Ii]t\|[Ii]s\|[Hh]as\|[Hh]ave\|[Tt]he\|[Tt]at\|[Tt]his\|[Oo]n\|[Oo]r\|[Tt]hen\|[Ii]f\|[Yy]ou\|[Aa]s\) .\+ \(and\|it\|is\|has\|have\|the\|that\|this\|on\|[Oo]r\|[Tt]hen\|[Ii]f\|[Yy]ou\|[Aa]s\) .*\) <\/s>$/\1/' | \
# sentences with many uriblanks are un-sentenced
  sed 's/^<s> \(\(.*uriblank.*\)\{2\}\) <\/s>/\1/' | \
# sentences that have orphaned ( or ) are un-sentenced
  sed 's/^<s> \(([^)]*\|.\+ ([^)]*\) <\/s>/\1/' | \
  sed 's/^<s> \(\(\|[^(]* \)).*\|)\) <\/s>/\1/' | \
# make sure that tags are in single lines (<s></s> is now no longer in single line with actual sentences)
  sed 's/</\n</g; s/>/>\n/g' | \
# restore quotes
  sed '/^[^<]/ s/"/\&quot;/g' | \
  sed "/^[^<]/ s/'/\&apos;/g" | \
# in non-XML-tag lines, make one token per line format
  sed '/^[^<]/ s/ /\n/g' | \
# in XML tags, turn _~_ into spaces (revert line 19)
  sed '/^</ s/_~_/ /g' | \
# delete empty lines
  sed '/^ *$/d' | \
# remove double " from <doc> tags (occured with some Last-Modified)
  sed '/^<doc url/ s/"" /" /g' | \
  sed '/^<doc url/ s/ ""/ "/g' | \
#  fix even more lines fucked up by ucto
  sed '/^< doc _ ~ _/ { s/ //g; s/_~_/ /g; }' | \

# TODO Re-enable after EmpiriST 
#  sed '/^</! {/^.\{35,\}/ { /^\([^-0-9]\{2,\}-\)\{2,\}/! {s/^.*$/noiseblank/} } }'
cat
