#!/bin/bash

# ==========================
# DONT ADAPT PAST THIS LINE!
# ==========================

set -e
set -u
input=$1
reg=$CORPUS_REGISTRY
data=$CORPUS_DATA

if [ ! -e $input ]
then
  exit
fi

pattr="-P pos -P lemma"
sattr="-S doc:0+url+ip+id+bdc+bdv+nbc+nbd+avgbpc+avgbpd+nbcprop+nbdprop+date+last-modified+country+region+city+qs+c_token+c_art+c_cli+c_emo+c_cased+c_gen+c_unk+c_blank+s_cli -S title -S keywords -S div:0+idx+bpc+bpv -S dup:0+idx+of -S s -S pc -S nc -S vc -0 meta"

unput=$(basename $input ".gz")
pref=$(basename $unput ".xml")
thisdata=${data}"/"${pref}
thisreg=${reg}"/"${pref}
corpus=`echo $pref | tr [:lower:] [:upper:]`

echo
echo =================================
echo === Summary of COW encode job ===
echo =================================
echo
echo "Input:          $input"
echo "Unpacked input: $unput"
echo "Corpus:         $corpus"
echo "Registry:       $thisreg"
echo "Data:           $thisdata"
echo "p-Attr:         $pattr"
echo "s-Attr:         $sattr"

# DEBUG
#exit

if [[ -e $thisdata ]]
then
  \rm -rf $thisdata
fi

if [[ -e $thisreg ]]
then
  \rm $thisreg
fi

gunzip -c $input > $unput
mkdir -p $thisdata

cwb-encode -xsB -c utf8 -d $thisdata -f $unput -R $thisreg $pattr $sattr

\rm $unput

cwb-make $corpus -M 8000
