#!/usr/bin/python

import codecs
import sys

UTF8Reader = codecs.getreader('utf8')
sys.stdin = UTF8Reader(sys.stdin)

UTF8Writer = codecs.getwriter('utf8')
sys.stdout = UTF8Writer(sys.stdout)

for l in sys.stdin:
  l = l.strip()

  if not l:
    continue

  if not lastl:
    lastl = l
    continue

  l_fields = l.split('\t')

