#!/bin/bash

# Pass:
# xml-infile token-infile outfile

# Define envvars:
# PARSERHOME   # location of Berkeley + model
# PARSER_TMP   # Where to put temp files.

# Important: Merging will only work if there are no XML-tags embedded within
# <s> ... </s> regions in the COW-XML file.

set -e
set -u

RESOURCES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

prefix="${PARSER_TMP}/${RANDOM}_$(basename $1 .gz)"
ospl="${prefix}_ospl.gz"
topo="${prefix}_topo.gz"
topoclean="${prefix}_topoclean.gz"
topoxml="${prefix}_topo.xml.gz"

echo $ospl

# Make one sentence per line from TOKEN infile.
python ${RESOURCES}/cow16-ospl.py ${2} ${ospl}

echo $topo

# Run the topological field parser on one sentence per line file.
gunzip -c ${ospl} | java -Xmx7g -jar ${PARSERHOME}/berkeleyParser.jar -gr ${PARSERHOME}/tuebadz_topf_no_edge.gr | gzip -c > ${topo}

exit

$RESOURCES/save_unparsables.py ${ospl} ${topo} ${topoclean}

# Make xml form parser output.
$RESOURCES/berkeley2sattr.py ${topoclean} |
  cut -f 1 |
  sed '/<\/\?>/d' |
  sed '/<\/\?pseudo>/d' | gzip -c >  ${topoxml}

# Merge xml files.
$RESOURCES/join-cowxml-topoxml.py ${1} ${topoxml} | gzip -c >  ${2}

# Remove temporary files.
\rm ${ospl}
\rm ${topo}
\rm ${topoclean}
\rm ${topoxml}
