#!/bin/bash

# Set $MARMOT_PATH to JAR and models
# Pass input file, output file, model (no path)

set -e
set -u

java -cp ${MARMOT_PATH}/marmot.jar marmot.morph.cmd.Annotator --model-file ${MARMOT_PATH}/de.marmot --test-file form-index=0,<(cat ${1}) --pred-file ${2}

