#!/bin/bash

# Pass input file (gz), output file (gz).

# Define envvars:
#    TT_MODEL_DE   (TT model abs. path)
#    TT_LEXIC_DE   (additional lexicon abs, path)
#    TT_TMP        (TMP path for ad-hoc lexicon and tmp tagging)

set -e
set -u

OPTS="-token -lemma -sgml -cap-heuristics -hyphen-heuristics -quiet"

# Generate ad-hoc-NN-lexicon for pretagging.
rnd=${RANDOM}
lexf="${TT_TMP}/$(basename ${1})_${rnd}_nnlexicon"
tmpf="${TT_TMP}/$(basename ${2})_${rnd}_tmp"

# 1. Generate unknown list for pretagging.
gunzip -c ${1} | cut -f 1 | tree-tagger $OPTS -lex ${TT_LEXIC_DE} $TT_MODEL_DE | gzip -c > ${tmpf}

# 2. Get SMOR analyses for unknowns.
smor-lemmatizer <(gunzip -c ${tmpf} | grep '	<unknown>' | cut -f 1) | sed 's/	\([A-Z]\+\|$\.\)\.[^	 ]\+/	\1/' | grep 'ADJ.\|NN\|NE' | sort -u | cow16-lexcompactor > ${lexf}

# 3. Final run with additional lexicon.
gunzip -c ${1} | cut -f 1 |
# Preserve sentence endings.
  sed 's/^$/\n<SÄTZÄNDÖ>\n/' |
  tree-tagger $OPTS -lex <(cat ${lexf} ${TT_LEXIC_DE}) $TT_MODEL_DE |
# Restore sentence ending blank lines.
  sed 's/^<SÄTZÄNDÖ>$//' |
# fix dupblank etc. annotation
  sed 's/^\(dupblank\|uriblank\|emailblank\|hashtagblank\|noiseblank\)	.\+$/\1	XY	(blank)/' |
# fix annotation of major smileys
  sed 's/^\([:;8=|\[][-o]\{0,1\}[][(){}OoKSsDPp]\+\)	.\+$/\1	XY	(smiley)/' |
  sed 's/^\&lt;3	.\+$/\&lt;3	XY	(smiley)/' |
  sed 's/^\&lt;\/3	.\+$/\&lt;\/3	XY	(smiley)/' |
  sed 's/^\(:[a-zäöüß]\+:\)	.\+$/\1	XY	(phpbbemo)/' |
  sed 's/^\(\*[a-zäöüßA-ZÄÖÜ0-9-]\+\*\)	.\+$/\1	XY	(asteriskative)/' |
# replace XML-unfriendly <unknown>
  sed 's/<unknown>$/(unknown)/' | gzip -c > ${2}

\rm ${tmpf}
\rm ${lexf}
