#!/bin/bash

# This tags with only treetagger lexicon. For virtual lexicon dumps.
# Pass input file (gz), output file (gz).

# Define envvars:
#    TT_MODEL_DE   (TT model abs. path)
#    TT_FILTER     (full path to filter-german-tags)

set -e
set -u

OPTS="-token -lemma -sgml -quiet"

# 3. Final run with additional lexicon.
gunzip -c ${1} | cut -f 1 |
# Preserve sentence endings.
  sed 's/^$/\n<SÄTZÄNDÖ>\n/' |
  tree-tagger $OPTS $TT_MODEL_DE |
  ${TT_FILTER} |
# Restore sentence ending blank lines.
  sed 's/^<SÄTZÄNDÖ>$//' |
# replace XML-unfriendly <unknown>
  sed 's/<unknown>$/(unknown)/' | gzip -c > ${2}

