#!/bin/bash

# This is like cow-topo-de, but it takes as input a file
# in one-sentence-per-line format, and the output of the
# Berkeley parser. Use this to resume when merging the xml-files
# did not succeed.


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Try to read PATHS from '' in the same directory this script resides in:
if [ -f $DIR/cow-topo-de.cfg ];
	then
		source $DIR/cow-topo-de.cfg
    echo "
Reading configuration from $DIR/cow-topo-de.cfg ..."
	else
		# if $DIR/resources-paths does not exist, use these:
		echo "No config file found, using defaults..."
		RESOURCES="/Users/felix/NLP/cow/src/corex"
		PARSERHOME="/Users/felix/NLP/berkelyparser/topoparser"
fi


type $RESOURCES/cow-mk-ospl.py >/dev/null 2>&1 || { echo >&2 "cow-mk-ospl.py not found in $RESOURCES"; exit 1; }

if [ ! -f  $PARSERHOME/berkeleyParser.jar ]; then
    echo "berkeleyParser.jar not found in $PARSERHOME"
		exit 1
fi

if [ ! -f  $PARSERHOME/tuebadz_topf_no_edge.gr ]; then
    echo "tuebadz_topf_no_edge.gr not found in $PARSERHOME"
		exit 1
fi

type $RESOURCES/save_unparsables.py >/dev/null 2>&1 || { echo >&2 "save_unparsables.py not found in $RESOURCES"; exit 1; }
type $RESOURCES/berkeley2sattr.py >/dev/null 2>&1 || { echo >&2 "berkeley2sattr.py not found in $RESOURCES"; exit 1; }
type $RESOURCES/join-cowxml-topoxml.py >/dev/null 2>&1 || { echo >&2 "join-cowxml-topoxml.py not found in $RESOURCES"; exit 1; }



#################################################################


prefix=$(basename $1 -ospl.tmp)
outfilename=$prefix-tf.xml

echo "Repairing parser output ..." 1>&2
$RESOURCES/save_unparsables.py $1 $2 > $prefix-topo-clean.tmp && \
# make xml form parser output:
echo "XMLify parser output ..." 1>&2
$RESOURCES/berkeley2sattr.py $prefix-topo-clean.tmp |\
# # grab the first column (tokens and xml):
cut -f 1 |\
# do some postprocessing:
# delete empty tags:
sed '/<\/\?>/d' |\
# delete <pseudo> and </pseudo> tags:
sed '/<\/\?pseudo>/d' |\
# delete 'chunks':
#sed '/<\/\?[^>]\+x[^>]*>/d' |\
# revert substitutions:
sed 's/^"$/\&quot;/g' |\
sed "s/'/\&apos;/g"|
sed 's/^\&$/\&amp;/g'|\
sed 's/^<$/\&lt;/g' |\
sed 's/^>$/\&gt;/g' |\
sed 's/\[/(/g' |\
sed 's/\]/)/g' > $prefix-topo-xml.tmp && \
# merge xml files:
echo "Merging structural attributes ..." 1>&2
$RESOURCES/join-cowxml-topoxml.py $prefix-nochunks.tmp $prefix-topo-xml.tmp >  $outfilename && \
# remove temporary files:
#\rm $prefix-topo-raw.tmp && \
#\rm $prefix-topo-xml.tmp && \
#\rm $prefix-nochunks.tmp && \
#\rm $prefix-ospl.tmp && \
echo "Output is in $outfilename" 1>&2 && \
# run xmlwf on outfilename
#echo "Checking XML ..." 1>&2 && \
#xmlwf $outfilename 1>&2 && \
echo "Done.
" 1>&2
