#!/bin/bash

OPTS="-token -lemma -sgml"
MODEL="/home/rsling/usr/local/treetagger/lib/english-par-linux-3.2-utf8.bin"

OPTS2="-token -sgml -eps 0.00000001 -hyphen-heuristics -quiet"
MODEL2="/home/rsling/usr/local/treetagger/lib/english-chunker-par-linux-3.2-utf8.bin"

FILTER=/home/rsling/usr/local/treetagger/cmd/filter-chunker-output.perl

OPTS3="-token -lemma -sgml -no-unknown -cap-heuristics -hyphen-heuristics"

sed 's/</\n</; s/>/>\n/' | \
  sed '/^</ s/ /_~_/g' | \
  sed '/^</! { s/\&quot;/"/g; s/\&apos;/'"'"'/g; s/\&amp;/\&/g; }' | \
  tree-tagger $OPTS $MODEL | \
  perl -nae 'if ($#F==0){print}else{print "$F[0]-$F[1]\n"}' | \
  sed 's/^</.-SENT\n</' | \
  tree-tagger $MODEL2 $OPTS2 | \
  $FILTER | \
  sed '/^\.	SENT/N; s/^\.	SENT\n</</' | \
  sed '/^\.	SENT/N; s/^\.	SENT\n\.	SENT/\.	SENT/' | \
  tree-tagger $OPTS $MODEL | \
  perl -pe 's/\tIN\/that/\tIN/;s/\tV[BDHV]/\tVB/' | \
  sed '/^</! { s/\&/\&amp;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g; } ' | \
  sed '/^$/d; s/>.\+$/>/' | \
  sed '/^</ s/_~_/ /g'  | \
  sed 's/^<NC>$/<nc>/' | \
  sed 's/^<\/NC>$/<\/nc>/' | \
  sed 's/^<VC>$/<vc>/' | \
  sed 's/^<\/VC>$/<\/vc>/' | \
  sed 's/^<PC>$/<pc>/' | \
  sed 's/^<\/PC>$/<\/pc>/' | \
  sed 's/^<ADVC>$/<advc>/' | \
  sed 's/^<\/ADVC>$/<\/advc>/' | \
  sed 's/^<ADJC>$/<adjc>/' | \
  sed 's/^<\/ADJC>$/<\/adjc>/' | \
  sed 's/^<PRT>$/<prt>/' | \
  sed 's/^<\/PRT>$/<\/prt>/' | \
  sed 's/^<CONJC>$/<conjc>/' | \
  sed 's/^<\/CONJC>$/<\/conjc>/' | \
  sed 's/^<LST>$/<lst>/' | \
  sed 's/^<\/LST>$/<\/lst>/' | \
  sed 's/^<INTJ>$/<intj>/' | \
  sed 's/^<\/INTJ>$/<\/intj>/' | \
  sed 's/<unknown>$/(unknown)/'
