#!/bin/bash

set -e

infile=$1
outfile=$2

infi=$(basename $outfile .xml.gz)
sentences="sent_${infi}"   # Name of file with extracted sentences.
deduped="dedup_${infi}"    # Name of file with deduped sentences.
tmpsplit="split_${infi}"   # prefix for the shuffle split
tmpshuf="_shuf"            # suffix for shuffled files
shufsize=34359738368       # size of split for shuf (bytes must fit in RAM)
sortsize=34359738368       # memory max for sort

cowinterleave -i $infile -s s |
  grep 'bdc="[a-j]"' |
  grep 'bpc="[a-f]"' |
  sed 's/ \(perfects\|pluperfects\|passives\|urldomain\|tld\|idx\|sourcecharset\|sourcedoctype\|region\|bdc\|ip\|nbc\|nbcprop\|nbd\|nbdprop\|avgbpc\|avgbpd\|date\|region\|city\|    \|crx_[^"]\+\|[scm]_[a-z]\+\|qs\)="[^"]\+"//g' |
  sed 's/ last-modified="/ last_modified="/' |
  sed 's/ last_modified="[^"]\+\(199[1-9]\|20[01][0-9]\)[^"]\+"/ last_modified="\1"/' > $sentences

echo
echo Sorting/deduping...
sort -T /scratch/rsling/tmp -S $sortsize -u -t">" -k 2 $sentences > $deduped
\rm $sentences

echo
echo Splitting for shuf...
split -a 10 -C $shufsize -d $deduped $tmpsplit
\rm $deduped

echo
echo Shuffling...
for f in `ls -1 $tmpsplit*`
do
  echo "  $f"
  shuf $f > $f$tmpshuf
  \rm $f
done

echo
echo Merging shuffled files and decoding interleave...
sort -m $tmpsplit*$tmpshuf  |
  sed 's/<ci_t \/>/	/g; s/<ci_l \/>/\n/g' |
  sed 's/	|\([^	]\)/	\1/g' |
  sed 's/\([^	]\)|\(	\|$\)/\1\2/g' |
  sed '/^$/d' |
  cut -f 1,2,3,4,5,6,7,10,11,12,13,14 |
  gzip -c > $outfile 
\rm $tmpsplit*$tmpshuf

echo
echo Done.
echo
