#!/bin/bash

echo "Checking ${1}..."

leadin='<?xml version="1.0" encoding="utf-8"?>\n<corpus>'
leadout='</corpus>'

cat <(echo -e ${leadin}) <(gunzip -c ${1} | sed '/^[^<]/ { s/&/\&amp;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g; }') <(echo -e ${leadout}) | xmlwf -r 

