#!/bin/bash

# Simple pipe filter for CWB/COW-XML data to NoSketchEngine format.

# We don't need the meta in interfaces.
grep -v '^<meta' |

# Extract crawl year and month and make sure attributes are always there, even if unknown.
sed '/^<doc / { s/\(last\)-\(modified="[^"]\+ \)\(Jan\|Feb\|Mar\|Apr\|May\|Jun\|Jul\|Aug\|Sep\|Oct\|Nov\|Dec\) \([12][90][0-9]\{2\}\)\( [^"]\+"\)/\1_\2\3 \4\5 lastmod_month="\3" lastmod_year="\4"/ }' | 
sed '/^<doc / { s/\(last\)-\(modified="[^"]\+"\)/\1_\2 lastmod_month="unknown" lastmod_year="unknown"/ }' |

# The same for date.
sed '/^<doc / { s/\date\(="[^"]\+ \)\(Jan\|Feb\|Mar\|Apr\|May\|Jun\|Jul\|Aug\|Sep\|Oct\|Nov\|Dec\) \([12][90][0-9]\{2\}\)\( [^"]\+"\)/crawl_date\1\2 \3\4 crawl_month="\2" crawl_year="\3"/ }' | 
sed '/^<doc / { s/ date\(="[^"]\+"\)/ crawl_date\1 crawl_month="unknown" crawl_year="unknown"/ }' |

# All unknowns should have same value.
sed 's/"_unk_"/"unknown"/g' |

# Extract host.
sed '/^<doc / { s/\( url="https\{0,1\}:\/\/\)\([^\/]\+\)\(\|\/\|%\)\([^"]*\)" /\1\2\3\5" host="\2" / }' |

# Extract TLD.
sed '/^<doc / { s/\( host="[^"]\+\.\)\([a-z]\+\|[0-9]\+\)" /\1\2" tld="\2" / }' |

# Create lc column for Noske.
sed '/^[^<]/ { s/^\([^	]\+\)	/\1	\L\1	/ }' |

# Create lemma_lc column, replacing (unknown) with token if only alpha and -.
sed '/^[^<]/ { s/^\([-[:alpha:]]\+\)	\([^	]\+\)	\([^	]\+\)	(\(unknown\))	\([^	]\+\)	\([^	]\+\)$/\1	\2	\3	(\4)	\5	\6	\L\1/ }' |
sed '/^[^<]/ { s/^\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	\((unknown)\)	\([^	]\+\)	\([^	]\+\)$/\1	\2	\3	\4	\5	\6	\4/ }' |
sed '/^[^<]/ { s/^\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	\([^	]\+\)	\([^	]\+\)$/\1	\2	\3	\4	\5	\6	\L\4/ }' |

# Create lempos attribute.
sed '/^[^<]/ { s/^\([^	]\+	[^	]\+\)	\([^	]\{2\}\)\([^	]*\)	\([^	]\+	[^	]\+	[^	]\+\)	\([^	]\+\)$/\1	\2\3	\4	\5	\5-\2/ }' 

